/*
 * This file is generated by jOOQ.
*/
package com.example.jooq.db.enums;


public enum AccessTokenTypeEnum {

    OAUTH("OAUTH"),

    NTLM("NTLM"),

    APIKEY("APIKEY"),

    BASIC("BASIC");

    private final String literal;

    AccessTokenTypeEnum(String literal) {
        this.literal = literal;
    }

}
