/*
 * This file is generated by jOOQ.
*/
package com.example.jooq.db.enums;


/**
 * This class is generated by jOOQ.
 */

public enum BtsTypeEnum {

    NONE("NONE"),

    JIRA("JIRA"),

    TFS("TFS"),

    RALLY("RALLY");

    private final String literal;

    BtsTypeEnum(String literal) {
        this.literal = literal;
    }
}
