/*
 * This file is generated by jOOQ.
*/
package com.example.jooq.db.enums;


public enum IssueGroupEnum  {

    PRODUCT_BUG("PRODUCT_BUG"),

    AUTOMATION_BUG("AUTOMATION_BUG"),

    SYSTEM_ISSUE("SYSTEM_ISSUE"),

    TO_INVESTIGATE("TO_INVESTIGATE"),

    NO_DEFECT("NO_DEFECT");

    private final String literal;

    IssueGroupEnum(String literal) {
        this.literal = literal;
    }
}
