/*
 * This file is generated by jOOQ.
*/
package com.example.jooq.db.enums;


public enum LaunchModeEnum {

    DEFAULT("DEFAULT"),

    DEBUG("DEBUG");

    private final String literal;

    LaunchModeEnum(String literal) {
        this.literal = literal;
    }

}
