/*
 * This file is generated by jOOQ.
*/
package com.example.jooq.db.enums;


public enum ProjectTypeEnum{

    INTERNAL("INTERNAL"),

    PERSONAL("PERSONAL"),

    UPSA("UPSA");

    private final String literal;

    ProjectTypeEnum(String literal) {
        this.literal = literal;
    }
}
