/*
 * This file is generated by jOOQ.
*/
package com.example.jooq.db.enums;


public enum ProjectRoleEnum {

    OPERATOR("OPERATOR"),

    CUSTOMER("CUSTOMER"),

    MEMBER("MEMBER"),

    PROJECT_MANAGER("PROJECT_MANAGER");

    private final String literal;

    private ProjectRoleEnum(String literal) {
        this.literal = literal;
    }
}
