/*
 * This file is generated by jOOQ.
*/
package com.example.jooq.db.enums;


public enum StatusEnum  {

    IN_PROGRESS("IN_PROGRESS"),

    PASSED("PASSED"),

    FAILED("FAILED"),

    STOPPED("STOPPED"),

    SKIPPED("SKIPPED"),

    INTERRUPTED("INTERRUPTED"),

    RESETED("RESETED"),

    CANCELLED("CANCELLED");

    private final String literal;

    StatusEnum(String literal) {
        this.literal = literal;
    }

}
