/*
 * This file is generated by jOOQ.
*/
package com.example.jooq.db.enums;


public enum TestItemTypeEnum {

    SUITE("SUITE"),

    STORY("STORY"),

    TEST("TEST"),

    SCENARIO("SCENARIO"),

    STEP("STEP"),

    BEFORE_CLASS("BEFORE_CLASS"),

    BEFORE_GROUPS("BEFORE_GROUPS"),

    BEFORE_METHOD("BEFORE_METHOD"),

    BEFORE_SUITE("BEFORE_SUITE"),

    BEFORE_TEST("BEFORE_TEST"),

    AFTER_CLASS("AFTER_CLASS"),

    AFTER_GROUPS("AFTER_GROUPS"),

    AFTER_METHOD("AFTER_METHOD"),

    AFTER_SUITE("AFTER_SUITE"),

    AFTER_TEST("AFTER_TEST");

    private final String literal;

	TestItemTypeEnum(String literal) {
        this.literal = literal;
    }

}
