/*
 * This file is generated by jOOQ.
*/
package com.example.jooq.db.enums;


public enum UserRoleEnum {

    ADMINISTRATOR("ADMINISTRATOR"),

    USER("USER");

    private final String literal;

    UserRoleEnum(String literal) {
        this.literal = literal;
    }

}
