/*
 * This file is generated by jOOQ.
*/
package com.example.jooq.db.enums;


public enum UserTypeEnum{

    INTERNAL("INTERNAL"),

    UPSA("UPSA"),

    GITHUB("GITHUB"),

    LDAP("LDAP");

    private final String literal;

    UserTypeEnum(String literal) {
        this.literal = literal;
    }

}
