/*
 * This file is generated by jOOQ.
*/
package com.example.jooq.db.tables.pojos;


import com.example.jooq.db.enums.BtsTypeEnum;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "bug_tracking_system", schema = "public", indexes = {
    @Index(name = "bug_tracking_system_pk", unique = true, columnList = "id ASC")
})
public class BugTrackingSystem implements Serializable {

    private static final long serialVersionUID = -926982194;

    private Integer     id;
    private String      url;
    private BtsTypeEnum type;

    public BugTrackingSystem() {}

    public BugTrackingSystem(BugTrackingSystem value) {
        this.id = value.id;
        this.url = value.url;
        this.type = value.type;
    }

    public BugTrackingSystem(
        Integer     id,
        String      url,
        BtsTypeEnum type
    ) {
        this.id = id;
        this.url = url;
        this.type = type;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, precision = 32)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "url", nullable = false)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Column(name = "type", nullable = false)
    public BtsTypeEnum getType() {
        return this.type;
    }

    public void setType(BtsTypeEnum type) {
        this.type = type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BugTrackingSystem (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
