/*
 * This file is generated by jOOQ.
*/
package com.example.jooq.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "dashboard", schema = "public", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"name", "project_id"})
}, indexes = {
    @Index(name = "dashboard_pk", unique = true, columnList = "id ASC"),
    @Index(name = "unq_name_project", unique = true, columnList = "name ASC, project_id ASC")
})
public class Dashboard implements Serializable {

    private static final long serialVersionUID = 1483758294;

    private Integer   id;
    private String    name;
    private Integer   projectId;
    private Timestamp creationDate;

    public Dashboard() {}

    public Dashboard(Dashboard value) {
        this.id = value.id;
        this.name = value.name;
        this.projectId = value.projectId;
        this.creationDate = value.creationDate;
    }

    public Dashboard(
        Integer   id,
        String    name,
        Integer   projectId,
        Timestamp creationDate
    ) {
        this.id = id;
        this.name = name;
        this.projectId = projectId;
        this.creationDate = creationDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, precision = 32)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "project_id", precision = 32)
    public Integer getProjectId() {
        return this.projectId;
    }

    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    @Column(name = "creation_date", nullable = false)
    public Timestamp getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Timestamp creationDate) {
        this.creationDate = creationDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Dashboard (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(projectId);
        sb.append(", ").append(creationDate);

        sb.append(")");
        return sb.toString();
    }
}
