/*
 * This file is generated by jOOQ.
*/
package com.example.jooq.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "issue_ticket", schema = "public", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"issue_id", "ticket_id"})
}, indexes = {
    @Index(name = "issue_ticket_pk", unique = true, columnList = "issue_id ASC, ticket_id ASC")
})
public class IssueTicket implements Serializable {

    private static final long serialVersionUID = -46769477;

    private Long issueId;
    private Long ticketId;

    public IssueTicket() {}

    public IssueTicket(IssueTicket value) {
        this.issueId = value.issueId;
        this.ticketId = value.ticketId;
    }

    public IssueTicket(
        Long issueId,
        Long ticketId
    ) {
        this.issueId = issueId;
        this.ticketId = ticketId;
    }

    @Column(name = "issue_id", nullable = false, precision = 64)
    public Long getIssueId() {
        return this.issueId;
    }

    public void setIssueId(Long issueId) {
        this.issueId = issueId;
    }

    @Column(name = "ticket_id", nullable = false, precision = 64)
    public Long getTicketId() {
        return this.ticketId;
    }

    public void setTicketId(Long ticketId) {
        this.ticketId = ticketId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IssueTicket (");

        sb.append(issueId);
        sb.append(", ").append(ticketId);

        sb.append(")");
        return sb.toString();
    }
}
