/*
 * This file is generated by jOOQ.
*/
package com.example.jooq.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "log", schema = "public", indexes = {
    @Index(name = "log_pk", unique = true, columnList = "id ASC")
})
public class Log implements Serializable {

    private static final long serialVersionUID = -709570325;

    private Long      id;
    private Timestamp logTime;
    private String    logMessage;
    private Long      itemId;
    private Timestamp lastModified;
    private Integer   logLevel;

    public Log() {}

    public Log(Log value) {
        this.id = value.id;
        this.logTime = value.logTime;
        this.logMessage = value.logMessage;
        this.itemId = value.itemId;
        this.lastModified = value.lastModified;
        this.logLevel = value.logLevel;
    }

    public Log(
        Long      id,
        Timestamp logTime,
        String    logMessage,
        Long      itemId,
        Timestamp lastModified,
        Integer   logLevel
    ) {
        this.id = id;
        this.logTime = logTime;
        this.logMessage = logMessage;
        this.itemId = itemId;
        this.lastModified = lastModified;
        this.logLevel = logLevel;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, precision = 64)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "log_time", nullable = false)
    public Timestamp getLogTime() {
        return this.logTime;
    }

    public void setLogTime(Timestamp logTime) {
        this.logTime = logTime;
    }

    @Column(name = "log_message", nullable = false)
    public String getLogMessage() {
        return this.logMessage;
    }

    public void setLogMessage(String logMessage) {
        this.logMessage = logMessage;
    }

    @Column(name = "item_id", nullable = false, precision = 64)
    public Long getItemId() {
        return this.itemId;
    }

    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    @Column(name = "last_modified", nullable = false)
    public Timestamp getLastModified() {
        return this.lastModified;
    }

    public void setLastModified(Timestamp lastModified) {
        this.lastModified = lastModified;
    }

    @Column(name = "log_level", nullable = false, precision = 32)
    public Integer getLogLevel() {
        return this.logLevel;
    }

    public void setLogLevel(Integer logLevel) {
        this.logLevel = logLevel;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Log (");

        sb.append(id);
        sb.append(", ").append(logTime);
        sb.append(", ").append(logMessage);
        sb.append(", ").append(itemId);
        sb.append(", ").append(lastModified);
        sb.append(", ").append(logLevel);

        sb.append(")");
        return sb.toString();
    }
}
